_BASE_: "../Mask2Former/configs/ade20k/semantic-segmentation/maskformer2_R50_bs16_160k.yaml"

DATASETS:
  TRAIN: ("ade20k_full_sem_seg_train",)
  TEST: ("ade20k_full_sem_seg_val",)

MODEL:
  META_ARCHITECTURE: "MaskFormer"
  WEIGHTS: ""
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    NUM_CLASSES: 847
    IGNORE_VALUE: 65535
  MASK_FORMER:
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: False

# Colab-friendly default sizing (override on CLI if you want the multi-scale ADE20K setup).
INPUT:
  DATASET_MAPPER_NAME: "mask_former_semantic"
  FORMAT: "RGB"
  SIZE_DIVISIBILITY: 32
  COLOR_AUG_SSD: True
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 512)
    SINGLE_CATEGORY_MAX_AREA: 1.0

SOLVER:
  IMS_PER_BATCH: 8
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.05
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.1
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 1.0e-6
  CHECKPOINT_PERIOD: 1000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

TEST:
  EVAL_PERIOD: 1000
  AUG:
    ENABLED: True

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 2

OUTPUT_DIR: "./outputs/ade20k_full_semseg"
VERSION: 2

